name: Build and deploy Docker image to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ secrets.RASPBERRY_PI_IP }}:${{ secrets.RASPBERRY_PI_PORT }}/myapp:latest

      - name: Push Docker image to registry
        run: |
          docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.RASPBERRY_PI_IP }}:${{ secrets.RASPBERRY_PI_PORT }}
          docker push ${{ secrets.RASPBERRY_PI_IP }}:${{ secrets.RASPBERRY_PI_PORT }}/myapp:latest

      - name: Deploy Docker image to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}
          username: ${{ secrets.RASPBERRY_PI_USERNAME }}
          key: ${{ secrets.RASPBERRY_PI_PRIVATE_KEY }}
          port: ${{ secrets.RASPBERRY_PI_PORT }}
          script: |
            docker pull ${{ secrets.RASPBERRY_PI_IP }}:${{ secrets.RASPBERRY_PI_PORT }}/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 9000:3000 ${{ secrets.RASPBERRY_PI_IP }}:${{ secrets.RASPBERRY_PI_PORT }}/myapp:latest
